import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [showcontact, setContact] = useState(false);


  function handleclick() {
    setContact(!showcontact);
  }

  return (
    <div className={styles.container}>
      <Head>
        
        <title>Ryan Webster</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.background}></div>
      <main className={styles.main}>
        
      <div className={styles.image}/>
        <h1 className={styles.title}>
          Ryan Webster
        </h1>

        <p className={styles.description}>
          Mobile Developer
        </p>
        {showcontact? 

            <div className={styles.grid}>
            <a 
              href="mailto:webstertrajano2003@gmail.com" 
              className={styles.card}
              target="_blank" rel="noopener noreferrer"
            >
              <p>Email &rarr;</p>

            </a>

            <a
                href="https://www.linkedin.com/in/ryanwebstert" 
                className={styles.card}
                target="_blank" rel="noopener noreferrer"
              >
                <p>Linkedin &rarr;</p>
                
              </a>

            <a
              href="https://api.whatsapp.com/send?phone=5565999257298&text=Ol%C3%A1"
              className={styles.card}
              target="_blank" rel="noopener noreferrer"
            >
              <p>WhatsApp &rarr;</p>
            
            </a>

            <a
              onClick={() => handleclick()}
              
              className={styles.card}
              
            >
              <p>Voltar &larr;</p>
              
            </a>
            </div>
                  
          :
              <div className={styles.grid}>
              <a 
                href="https://github.com/ryanwebstert" 
                className={styles.card}
                target="_blank" rel="noopener noreferrer"
              >
                <p>GitHub &rarr;</p>
              
              </a>

              <a
                href="https://www.linkedin.com/in/ryanwebstert" 
                className={styles.card}
                target="_blank" rel="noopener noreferrer"
              >
                <p>Linkedin &rarr;</p>
                
              </a>

              <a
                href="https://webster-blog.vercel.app/"
                className={styles.card}
                target="_blank" rel="noopener noreferrer"
              >
                <p>Webster Blog &rarr;</p>
              
              </a>

              <a
                onClick={() => handleclick()}
                className={styles.card}
                
              >
                <p>Contato &rarr;</p>
                
              </a>
            </div>
}
        
      </main>
    </div>
  )
}

export default Home
